version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: book-quotes-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "0.0.0.0:${MONGO_PORT:-27017}:27017"  # Bind to all interfaces
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: book-quotes-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-5000}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "0.0.0.0:${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"  # Bind to all interfaces
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_APP_TITLE: ${VITE_APP_TITLE}
    container_name: book-quotes-frontend
    restart: unless-stopped
    ports:
      - "0.0.0.0:${FRONTEND_PORT:-4000}:80"  # Bind to all interfaces
    depends_on:
      - backend

volumes:
  mongodb_data: